version: "3.9"
services:
  frontend:
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
  backend:
    environment:
      - LOG_LEVEL=debug
    stdin_open: true
    tty: true
